<a href="https://colab.research.google.com/github/ToddMG/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/module1-afirstlookatdata/LS_DS_111_A_First_Look_at_Data_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lambda School Data Science - A First Look at Data



## Lecture - let's explore Python DS libraries and examples!

The Python Data Science ecosystem is huge. You've seen some of the big pieces - pandas, scikit-learn, matplotlib. What parts do you want to see more of?

In [0]:
# TODO - we'll be doing this live, taking requests
# and reproducing what it is to look up and learn things

print('I\'ve heard a lot about tensor flow, conveniently enough Rudy Enriquez has a notebook on Tensors.')

I've heard a lot about tensor flow, conveniently enough Rudy Enriquez has a notebook on Tensors.


## Assignment - now it's your turn

Pick at least one Python DS library, and using documentation/examples reproduce in this notebook something cool. It's OK if you don't fully understand it or get it 100% working, but do put in effort and look things up.

##Intro
From what I understand, tensors are the alternative to numpy multi-dimensional arrays (that only use one data type) that can harness GPU strength.


After doing some research, *tensors can be generalized as multi-dimensional matrices and they can range from 0 to N dimensions*.

Unlike Matrices, tensors are *dynamic* and tend to warp as they're used in operation with other entities.


There are multiple ways to create tensors from numpy:

## **Dependencies**

In [0]:
import numpy as np
import torch

##Code

In [0]:
# TODO - your code here
# Use what we did live in lecture as an example

myArray = np.arange(6,10)

myTensor1 = torch.from_numpy(myArray)
myTensor2 = torch.as_tensor(myArray)
myTensor3 = torch.tensor(myArray)

##According to Rudy, the difference between the methods is:
- The first and second method creates a variable that shares memory with the original array. 
- The last method creates a copy.

Examples of modifying the different methods:

In [0]:
#Check the elements first
print(f"Elements of myArray: {myArray}")
print(f"Elements of myTensor1: {myTensor1}")
print(f"Elements of myTensor3: {myTensor3}")

Elements of myArray: [6 7 8 9]
Elements of myTensor1: tensor([6, 7, 8, 9])
Elements of myTensor3: tensor([6, 7, 8, 9])


In [0]:
#Change the elements
myArray[2] = 2340

print(f"Elements of myArray: {myArray}")
print(f"Elements of myTensor1: {myTensor1}")
print(f"Elements of myTensor3: {myTensor3}")

#Note to self: I'd be interested to know why there's extra blank spaces between the modified array.

Elements of myArray: [   6    7 2340    9]
Elements of myTensor1: tensor([   6,    7, 2340,    9])
Elements of myTensor3: tensor([6, 7, 8, 9])


##Now let's have some fun with third-order tensors


In [0]:
#Define the Arrays
xArray1 = np.random.randint(5, size=(3, 3, 3))
xArray2 = np.random.randint(6,10, size=(3, 3 ,3))

#Create the Tensors as copies
nArray1 = torch.tensor(xArray1)
nArray2 = torch.tensor(xArray2)

#Check data types
print(f"Data type of tensor 1: {nArray1.dtype}")
print(f"Data type of tensor 2: {nArray2.dtype}\n")

print(f"Tensor #1:\n {nArray1}")
print(f"\nTensor #2:\n {nArray2}")

Data type of tensor 1: torch.int64
Data type of tensor 2: torch.int64

Tensor #1:
 tensor([[[2, 3, 0],
         [1, 2, 4],
         [4, 2, 4]],

        [[3, 0, 3],
         [3, 1, 3],
         [1, 0, 4]],

        [[4, 4, 0],
         [2, 0, 1],
         [3, 4, 1]]])

Tensor #2:
 tensor([[[8, 7, 9],
         [6, 9, 7],
         [9, 6, 9]],

        [[8, 6, 9],
         [7, 9, 7],
         [9, 8, 9]],

        [[6, 7, 9],
         [8, 9, 6],
         [6, 6, 7]]])


Tensor Addition and Subtraction

In [0]:
print("Array #1 + Array #2:")
print(nArray1 + nArray2)

print("\nArray #1 - Array #2:")
print(nArray1 - nArray2)


Array #1 + Array #2:
tensor([[[10, 10,  9],
         [ 7, 11, 11],
         [13,  8, 13]],

        [[11,  6, 12],
         [10, 10, 10],
         [10,  8, 13]],

        [[10, 11,  9],
         [10,  9,  7],
         [ 9, 10,  8]]])

Array #1 - Array #2:
tensor([[[-6, -4, -9],
         [-5, -7, -3],
         [-5, -4, -5]],

        [[-5, -6, -6],
         [-4, -8, -4],
         [-8, -8, -5]],

        [[-2, -3, -9],
         [-6, -9, -5],
         [-3, -2, -6]]])


Tensor Hadamard Product (Element-wise multiplication)

In [0]:
print("nArray1 * nArray2")
print(nArray1 * nArray2)

nArray1 * nArray2
tensor([[[16, 21,  0],
         [ 6, 18, 28],
         [36, 12, 36]],

        [[24,  0, 27],
         [21,  9, 21],
         [ 9,  0, 36]],

        [[24, 28,  0],
         [16,  0,  6],
         [18, 24,  7]]])


##Voila! That's all she wrote. For now.

### Assignment questions

After you've worked on some code, answer the following questions in this text block:

1.  Describe in a paragraph of text what you did and why, as if you were writing an email to somebody interested but nontechnical.

Having heard a lot about a specific term, I decided to read Rudy Enriquez's brief intro on "Tensors". Having understood Tensors' use, I decided to mimic Rudy's demonstration of the difference between references and copies of an array. In the process, I learned print formatting and decided to make use of the scan function. I also did some research on Tensors and their use in the Data Science field. They're primarily seen within deep learning models. Vectors are otherwise known as first-order tensors, while matrices are known as second-order tensors. I then proceeded to do some 3D Tensor operations for fun.

2.  What was the most challenging part of what you did?

Finding the right arguments for creating a random 3D Array/Tensor.It wasn't all that hard, but it was the hardest part of my test.

3.  What was the most interesting thing you learned?

I'm starting to wrap my head around 3D Arrays. Tensors seem to have limitless dimensions, so it might get nasty fast. Getting better at handling lots of data is just another part of this journey!

4.  What area would you like to explore with more time?

Tensor's real world usage versus matrices. What real benefits do 2D Tensors (identical to matrices from what I understand) offer?



## Stretch goals and resources

Following are *optional* things for you to take a look at. Focus on the above assignment first, and make sure to commit and push your changes to GitHub (and since this is the first assignment of the sprint, open a PR as well).

- [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/)
- [scikit-learn documentation](http://scikit-learn.org/stable/documentation.html)
- [matplotlib documentation](https://matplotlib.org/contents.html)
- [Awesome Data Science](https://github.com/bulutyazilim/awesome-datascience) - a list of many types of DS resources

Stretch goals:

- Find and read blogs, walkthroughs, and other examples of people working through cool things with data science - and share with your classmates!
- Write a blog post (Medium is a popular place to publish) introducing yourself as somebody learning data science, and talking about what you've learned already and what you're excited to learn more about.

#Here's my [blogpost!](https://medium.com/@ToddMG_/first-day-as-a-data-science-student-40ca2958a90)
