# Lambda School Data Science - A First Look at Data



## Lecture - let's explore Python DS libraries and examples!

The Python Data Science ecosystem is huge. You've seen some of the big pieces - pandas, scikit-learn, matplotlib. What parts do you want to see more of?

In [0]:
# TODO - we'll be doing this live, taking requests
# and reproducing what it is to look up and learn things

#This is a change hello

## Assignment - now it's your turn

Pick at least one Python DS library, and using documentation/examples reproduce in this notebook something cool. It's OK if you don't fully understand it or get it 100% working, but do put in effort and look things up.

In [10]:
import numpy as np

b = np.arange(1, 30, 5)
print(b)




[ 1  6 11 16 21 26]


In [12]:

b = b.reshape(3,2)
print(b)


[[ 1  6]
 [11 16]
 [21 26]]


In [15]:
c = np.arange(0, 30, 5)
print(c)

[ 0  5 10 15 20 25]


### Assignment questions

After you've worked on some code, answer the following questions in this text block:

1.  Describe in a paragraph of text what you did and why, as if you were writing an email to somebody interested but nontechnical.

   First I made a list by extracting every fifth number from 1 to 30. I then turned this list into a two dimensional list,

2.  What was the most challenging part of what you did?

    There was nothing really challenging about what I did. I was trying to figure out what purpose there is in turning a list into a 2D array. Since the data in 2D represents different axes I don't see how that data could ever end up in a 1 dimensional list.

3.  What was the most interesting thing you learned?

  I didn't learn anything necessarily, but I notice that since I got numbers in a range from 1-30 instead of 0-30 it brought back factors of 6 instead of 5. I do know better, but apparently starting from 0 isn't engrained yet.

4.  What area would you like to explore with more time?
  
  I already answered this question, I want to see in what context you would need to transform a list into a 2D list.




## Stretch goals and resources

Following are *optional* things for you to take a look at. Focus on the above assignment first, and make sure to commit and push your changes to GitHub (and since this is the first assignment of the sprint, open a PR as well).

- [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/)
- [scikit-learn documentation](http://scikit-learn.org/stable/documentation.html)
- [matplotlib documentation](https://matplotlib.org/contents.html)
- [Awesome Data Science](https://github.com/bulutyazilim/awesome-datascience) - a list of many types of DS resources

Stretch goals:

- Find and read blogs, walkthroughs, and other examples of people working through cool things with data science - and share with your classmates!
- Write a blog post (Medium is a popular place to publish) introducing yourself as somebody learning data science, and talking about what you've learned already and what you're excited to learn more about.